version: "3.8"
services:
  db:
    image: postgres:10.1
    volumes:
    - ./tmp/db:\\Program Files\\PostgreSQL\\10\\data
    environment:
      POSTGRES_PASSWORD: ${UNK_ANA_PG_PASSWORD}
      POSTGRES_USER: ${UNK_ANA_PG_USER}
    container_name: unk-postgres
    env_file:
    - ./docker/.env
  redis:
    image: 'redis:5-alpine'
    command: redis-server
    container_name: unk-redis
    ports:
    - '6379:6379'
      #volumes:
    #'redis:/data'
  #  web:
  #    build: .
  #    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  #    image: unk-webapp:${TAG-stable}
  #    container_name: web-app
  #    env_file:
  #    - ./docker/.env
  #    volumes:
  #    - .:/myapp
  #    ports:
  #    - "3000:3000"
  #    depends_on:
  #    - db
  #    - redis
  sidekiq:
    build: .
    command: bundle exec sidekiq
    entrypoint: []
    container_name: unk-sidekiq
    image: unk-sidekiq:${TAG-stable}
    env_file:
    - ./docker/.env
    volumes:
    - '.:/myapp'
    - '/myapp/tmp' # don't mount tmp directory
    depends_on:
    - db
    - redis
