default: &default
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  url: <%= ENV.fetch("UNK_ANA_REDIS_URI") %>
  channel_prefix: <%= ENV.fetch("UNK_ANA_REDIS_CHANNEL_PREFIX") { "unk_" + Rails.env } %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
