development:
  adapter: redis
  url: <%= ENV.fetch("UNK_ANA_REDIS_URI") %>
  channel_prefix: <%= ENV.fetch("UNK_ANA_REDIS_CHANNEL_PREFIX") %>

test:
  adapter: redis
  url: <%= ENV.fetch("UNK_ANA_REDIS_URI") %>
  channel_prefix:  <%= ENV.fetch("UNK_ANA_REDIS_CHANNEL_PREFIX") %>

staging:
  adapter: redis
  url: <%= ENV.fetch("UNK_ANA_REDIS_URI")%>
  channel_prefix:  <%= ENV.fetch("UNK_ANA_REDIS_CHANNEL_PREFIX") %>

production:
  adapter: redis
  url: <%= ENV.fetch("UNK_ANA_REDIS_URI")%>
  channel_prefix: <%= ENV.fetch("UNK_ANA_REDIS_CHANNEL_PREFIX") %>
