development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://127.0.0.1:6379/1" } %>
  channel_prefix: track-web_development


test:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://127.0.0.1:6379/1" } %>
  channel_prefix: track-web_production


production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://127.0.0.1:6379/1" } %>
  channel_prefix: track-web_production
